-- Synthetic fixtures only, transaction rollback. Never selects a customer's store.
begin;
create temporary table menu_test_result(name text,passed boolean);
do $$
declare
  owner_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid(); viewer uuid:=gen_random_uuid();
  org uuid:=gen_random_uuid(); store uuid:=gen_random_uuid(); other_store uuid:=gen_random_uuid(); item uuid:=gen_random_uuid();
  doc uuid:=gen_random_uuid(); purchase uuid:=gen_random_uuid(); waste uuid:=gen_random_uuid(); lines jsonb; denied boolean;
  manual_key uuid:=gen_random_uuid();
begin
  insert into auth.users(id,email) values(owner_id,owner_id||'@example.invalid'),(staff_id,staff_id||'@example.invalid'),(stranger,stranger||'@example.invalid'),(viewer,viewer||'@example.invalid');
  insert into public.user_profiles(user_id,status,role) values(owner_id,'active','user'),(staff_id,'active','user'),(stranger,'active','user'),(viewer,'active','user') on conflict(user_id) do update set status='active',role='user';
  insert into public.organizations(id,name,status) values(org,'MENU SYNTHETIC','active');
  insert into public.stores(id,organization_id,industry_type_key,name,status) values(store,org,'restaurant','MENU SYNTHETIC','active'),(other_store,org,'restaurant','OTHER SYNTHETIC','active');
  insert into public.organization_members(organization_id,user_id,role_key,status) values(org,owner_id,'org_owner','active');
  insert into public.store_memberships(organization_id,store_id,user_id,email,role_key,status) values(org,store,staff_id,staff_id||'@example.invalid','staff','active'),(org,store,viewer,viewer||'@example.invalid','viewer','active');
  insert into public.items(id,organization_id,store_id,industry_type_key,name,unit,is_stock_managed) values(item,org,store,'restaurant','SYNTHETIC ITEM','箱',true);
  lines:=jsonb_build_array(jsonb_build_object('item_id',item,'name','SYNTHETIC ITEM','quantity',5,'unit','箱'));
  if public.menu_actor_allowed(stranger,store) or public.menu_actor_allowed(staff_id,other_store) or public.menu_actor_allowed(viewer,store) or public.menu_actor_allowed(staff_id,store,true) then raise exception 'AUTH MATRIX'; end if;
  insert into menu_test_result values('no-membership / other-store / viewer / manager-only denied',true);
  perform public.set_menu_availability(staff_id,store,item,'sold_out');
  if not exists(select 1 from public.items where id=item and availability='sold_out') then raise exception 'STATUS'; end if;
  perform public.set_menu_availability(staff_id,store,item,'available');
  update public.user_profiles set status='suspended' where user_id=staff_id;
  if public.menu_actor_allowed(staff_id,store) then raise exception 'SUSPENDED'; end if;
  update public.user_profiles set status='active' where user_id=staff_id;
  insert into menu_test_result values('availability reversible / suspended denied',true);
  perform public.save_stock_document(staff_id,store,doc,'receipt','TEST',current_date,lines,'',0);
  perform public.save_stock_document(staff_id,store,doc,'receipt','TEST',current_date,lines,'',0);
  if exists(select 1 from public.inventory_stocks where item_id=item and quantity<>0) then raise exception 'DRAFT CHANGED STOCK'; end if;
  perform public.transition_stock_document(staff_id,store,doc,'archive',1);
  perform public.transition_stock_document(staff_id,store,doc,'restore',2);
  perform public.transition_stock_document(staff_id,store,doc,'confirm',3);
  perform public.transition_stock_document(staff_id,store,doc,'confirm',3);
  if (select quantity from public.inventory_stocks where item_id=item)<>5 then raise exception 'DUPLICATE RECEIPT'; end if;
  insert into menu_test_result values('draft / archive / restore / confirm idempotency',true);
  perform public.save_stock_document(owner_id,store,purchase,'purchase','TEST',current_date,lines,'',0);
  perform public.transition_stock_document(owner_id,store,purchase,'confirm',1);
  if (select quantity from public.inventory_stocks where item_id=item)<>5 then raise exception 'PURCHASE CHANGED STOCK'; end if;
  denied:=false;begin perform public.transition_stock_document(staff_id,store,doc,'reverse',4);exception when others then denied:=true;end;
  if not denied then raise exception 'STAFF REVERSE'; end if;
  perform public.transition_stock_document(owner_id,store,doc,'reverse',4);
  perform public.transition_stock_document(owner_id,store,doc,'reverse',4);
  if (select quantity from public.inventory_stocks where item_id=item)<>0 then raise exception 'REVERSE'; end if;
  insert into menu_test_result values('purchase does not receive / manager reverse idempotency',true);
  perform public.save_stock_document(staff_id,store,waste,'waste','',current_date,lines,'破損',0);
  denied:=false;begin perform public.transition_stock_document(staff_id,store,waste,'confirm',1);exception when others then denied:=true;end;
  if not denied or (select status from public.stock_documents where id=waste)<>'draft' then raise exception 'NEGATIVE STOCK / ATOMICITY'; end if;
  denied:=false;begin perform public.save_stock_document(staff_id,store,waste,'waste','',current_date,jsonb_set(lines,'{0,unit}','"個"'),'破損',1);exception when others then denied:=true;end;
  if not denied then raise exception 'UNIT'; end if;
  denied:=false;begin perform public.save_stock_document(stranger,store,gen_random_uuid(),'receipt','',current_date,lines,'',0);exception when others then denied:=true;end;
  if not denied then raise exception 'UNAUTHORIZED RPC'; end if;
  if has_function_privilege('authenticated','public.save_stock_document(uuid,uuid,uuid,text,text,date,jsonb,text,integer,uuid)','execute') or has_function_privilege('anon','public.set_menu_availability(uuid,uuid,uuid,text)','execute') or has_table_privilege('authenticated','public.stock_documents','select') then raise exception 'API ACL'; end if;
  insert into menu_test_result values('negative / unit mismatch / actor / direct API rejected',true);
  perform public.manual_inventory_change(owner_id,store,item,'receipt',10,0,'合成確認',manual_key,2,100);
  perform public.manual_inventory_change(owner_id,store,item,'receipt',10,0,'合成確認',manual_key,2,100);
  if (select quantity from public.inventory_stocks where item_id=item)<>10 then raise exception 'MANUAL DUPLICATE'; end if;
  denied:=false;begin perform public.manual_inventory_change(owner_id,store,item,'stocktake',8,0,'合成確認',gen_random_uuid(),2,null);exception when others then denied:=true;end;
  if not denied then raise exception 'STALE STOCKTAKE'; end if;
  perform public.manual_inventory_change(owner_id,store,item,'stocktake',8,10,'合成確認',gen_random_uuid(),2,null);
  if (select quantity from public.inventory_stocks where item_id=item)<>8 then raise exception 'STOCKTAKE'; end if;
  insert into menu_test_result values('manual idempotency / stale stocktake guard / atomic adjustment',true);
end $$;
select * from menu_test_result;
rollback;
